config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  resources :books
  resources :categories
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :review
  has_many :activities, as: :target

  mount_uploader :image, ImageUploader
  has_attached_file :image, styles: {medium: Setting.medium, thumb: Setting.thumb}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :title, presence: true, length: {minimum: 6}
  validates :author, presence: true
  validates :num_of_page, presence: true
  validates :category_id, presence: true
  validates :publish_date, presence: true

  def self.rate? book_id, condition
    active = Activity.where user_id: current_user.id, target_id: book_id,
      action: condition
    active.any?
  end

  scope :recent, -> {order "updated_at DESC"}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, except: [:create, :new]
  before_action :all_category, only: [:new, :edit]

  def index
    @books = Book.recent.paginate page: params[:page], per_page: Settings.per_page
  end

  def show
    @reviews = @book.reviews
    @rating = @book.rating
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new book_params
    if book.save
      flash[:success] = t "success_book_create"
      redirect_to books_path
    else
      flash[:info] = t "error_create"
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "update_book_success"
      redirect_to books_path
    else
      flash[:error] = t "update_book_error"
      render :back
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t "delete_book_success"
      redirect_to books_path
    else
      flash[:success] = t "delete_book_error"
      render :back
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :publish_date, :author, :num_of_page,
      :category_id, :image
  end

  def load_book
    @book = Book.find_by_id params[:id]
    unless @book
      flash[:success] = t "error_return_home"
      redirect_to root_url
    end
  end

  def load_category
    @categories = Category.all
  end
end

app/views/books/_book.html.erb
<% @books.each do |book| %>
  <tr>
    <td><%= book.category.name %></td>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= image_tag book.image.url :thumb if book.image? %></td>
    <td><%= link_to t("edit"), edit_book_path book.id,
      class: "fa fa-pencil-square-o" %>
    </td>
    <td>
      <%= link_to t("delete"), book_path book.id, method:"delete",
        data: {confirm: t("confirm")}, class: "fa fa-pencil-square-o" %>
    </td>
  </tr>
<% end %>

app/views/books/edit.html.erb
<div class="inner_page">
  <div class="book">
    <h1><%= t".edit_book" %></h1><br>
    <div class="bookform">
      <%= form_for @book do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.select :category_id, @categories.collect { |c| [ c.name, c.id ] },
          class: "select-category", include_blank: t".select" %>
        <%= f.text_field :title, placeholder: t("book_title"), class: "input-text" %>
        <%= f.text_field :author, placeholder: t("book_author"), class: "input-text" %>
        <%= f.number_field :num_of_page, placeholder: t("num"), class: "input-text" %>
        <%= f.text_field :publish_date, placeholder: t("date"), class: "input-text" %>
        <div>
          <label for="file-upload" class="custom-file-upload">
            <i class="fa fa-cloud-upload"></i><%= t".upload" %>
          </label>
          <%= f.file_field :image, id: "file-upload", style: "display:none;",
            onchange: "previewFile()" %>
        </div>
        <button type="submit" class="btn btn-submit"><%= t ".update" %></button>
        <div class="imgbook">
          <%= image_tag "book.jpg", id: "imgtag" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="inner_page">
  <div class="signup">
    <div class="tbl">
    <table>
      <tr>
        <th><%= t".cate" %></th>
        <th><%= t".title" %></th>
        <th><%= t".author" %></th>
        <th><%= t".image" %></th>
        <th colspan="2"><%= t".action" %></th>
      </tr>
      <%= render @books %>
    </table>
    <%= will_paginate @books %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="inner_page">
  <div class="book">
    <h1><%= t"add" %></h1><br>
    <div class="bookform">
      <%= form_for @book, html: {multipart: true} do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.select :category_id, @categories.collect { |c| [ c.name, c.id ] },
          class: "blah", include_blank: t "select_category" %>
        <%= f.text_field :title, placeholder: t("book_title"), class: "input-text" %>
        <%= f.text_field :author, placeholder: t("book_author"), class: "input-text" %>
        <%= f.number_field :num_of_page, placeholder: t("num"), class: "input-text" %>
        <%= f.text_field :publish_date, placeholder: t("date"), class: "input-text" %>
        <div>
          <label for="file-upload" class="custom-file-upload">
            <i class="fa fa-cloud-upload"></i><%= t"custom" %>
          </label>
          <%= f.file_field :image, id: "file-upload", style: "display:none;", onchange: "previewFile()" %>
        </div>
        <button type="submit" class="btn btn-submit"><%= t "create" %></button>
      <% end %>
    </div>
    <div class="imgbook">
      <%= image_tag "book.jpg", id: "imgtag" %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div id="messages_product_view"></div>
<div class="product-view">
  <div class="product-essential">
    <div class="product-img-box">
      <%= image_tag @book.image.url %>
    </div>
    <div class="product-shop">
      <div class="product-name">
      <% if login? %>
        <div class="buttonHolder">
        <% unless check_rate @book.id, t"mark" %>
          <%= link_to "", actives_path book_id: @book.id, key: t"mark",
            class: "action tick", title: t"statuss", remote: true %>
        <% end %>
        <% unless check_rate @book.id, t"readed" %>
          <%= link_to "", actives_path book_id: @book.id, key: t"readed",
            class: "action heart", title: t"statuss", remote: true  %>
        <% end %>
        <% unless check_rate @book.id, t"favorite" %>
          <%= link_to "", actives_path book_id: @book.id, key: t"favorite",
            class: "action flower", title: t"statuss", remote: true  %>
        <% end %>
        </div>
      <% end %>
        <h1><%= t ".title" %> <%= @book.title %></h1>
      </div>
      <p class="availability in-stock"><%= t ".author" %>
        <span><%= @book.author %></span>
      </p>
      <p class="availability-only">
        <span title="Only 10000 left"><%= t ".number" %>
          <strong><%= @book.num_of_page %></strong>
        </span>
      </p>
      <p class="availability-only">
        <span><%= ".pusblish" %> <strong><%= @book.publish_date %></strong></span>
      </p>
      <div class="clear"></div>
      <%= render "ratings/rating" %>
      <hr>
      <h1><%= link_to t"write", new_review_path book_id: @book.id %></h1>
      <div class="clear"></div>
    </div>
    <div class="clearer"></div>
  </div>
  <%= render "reviews/list_review" %>
</div>