config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  resources :books
  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
  belongs_to :parent, class_name: Category.name
  has_many :categories, foreign_key: :parent_id

  validates :name, presence: true, uniqueness: true

  scope :order_by_name, -> {order :name}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order_by_name.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new load_category
    if category.save
      flash[:success] =  t "success_category_create"
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes categories_params
      flash[:success] =  t "update_category_success"
      redirect_to categories_path
    else
      flash[:danger] = t "update_category_error"
      render :back
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "delete_category_success"
      redirect_to categories_path
    else
      flash[:danger] = @category.errors.full_messages
      redirect_to :back
    end
  end

  private
  def categories_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find_by_id params[:id]
    unless @category
      flash[:danger] = t "error_return_home"
      redirect_to root_url
    end
  end
end

app/views/categories/_category.html.erb
<% @categories.each_with_index do |category, index| %>
  <tr>
    <td>
      <%= index_continue params[:page], index, Settings.per_page %>
    </td>
    <td><%= category.name %></td>
    <td><%= category.parent.name %></td>
    <td>
      <%= link_to t "edit", edit_category_path category,
        class: "fa fa-pencil-square-o" %>
    </td>
    <td>
      <%= link_to t "delete", category_path category, method: :delete,
        data: {confirm: t ".confirm"}, class: "fa fa-pencil-square-o" %>
    </td>
  </tr>
<% end %>
<%= will_paginate @categories %>

app/views/categories/_form_category.html.erb
<%= form_for @category do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: t(".name"), class: "input-text" %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-submit"><%= t ".create" %></button>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="inner_page">
  <div class="signup">
    <h1><%= t ".edit_category" %></h1>
    <%= render "form_category" %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="inner_page">
  <div class="signup">
    <div class="tbl">
      <table>
        <tr>
          <th><%= t "id" %></th>
          <th><%= t "cate_name" %></th>
          <th><%= t "cate_parent" %></th>
          <th colspan="2" ><%= t "action" %></th>
        </tr>
        <%= render @categories %>
      </table>
    </div>
    <%= will_paginate @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="inner_page">
  <div class="signup">
    <h1><%= t ".add_new" %></h1>
    <%= render "form_category" %>
  </div>
</div>